### ISSUE TITLE
Add multiple state column support to ctf.py

### ISSUE THREAD

**Issue by ETaSky** [cameronmartino/gemelli#25]
Currently, the ctf() function in the ctf.py script seems to only accept 1 state column. Just copy part of standalone_ctf codes should be able to fix the issue.
--Jincheng

**Comment by cameronmartino** [comment]
Hi @ETaSky,

The `ctf_helper` can do this. The reason the `ctf` function does not take multiple states is that in QIIME2 it is not allowed to output a list of objects. This is an enhancement that may have to wait for some updated to q2CLI that are coming.
